/* eslint-disable global-require */
// @ts-nocheck
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./app/ui/**/*.{js,jsx,ts,tsx}', './client/*.html'],
  darkMode: 'class',
   theme: {
      backgroundOpacity: {
         10: '0.1',
         20: '0.2',
         95: '0.95',
        },
        safelist: [
          '-mx-1.5',
          '-my-1.5',
          'appearance-none',
          'bg-green-100',
          'bg-green-50',
          'bg-indigo-600',
          'bg-red-50',
          'bg-white',
          'block',
          'border',
          'border-gray-300',
          'border-transparent',
          'cursor-pointer',
          'flex',
          'focus:border-indigo-500',
          'focus:outline-none',
          'focus:ring-2',
          'focus:ring-indigo-500',
          'focus:ring-offset-2',
          'focus:ring-offset-red-50',
          'focus:ring-red-600',
          'font-medium',
          'hover:bg-indigo-700',
          'hover:bg-red-100',
          'hover:text-indigo-500',
          'inline-flex',
          'justify-center',
          'justify-end',
          'ml-auto',
          'mt-0',
          'mt-1',
          'mt-8',
          'p-1.5',
          'p-4',
          'pl-3',
          'placeholder-gray-400',
          'px-3',
          'px-4',
          'py-2',
          'py-8',
          'ring-green-600',
          'ring-offset-green-50',
          'rounded-md',
          'shadow',
          'shadow-sm',
          'sm:max-w-md',
          'sm:mx-auto',
          'sm:px-10',
          'sm:rounded-lg',
          'sm:text-sm',
          'sm:w-full',
          'space-y-6',
          'sr-only',
          'text-gray-700',
          'text-green-500',
          'text-green-800',
          'text-indigo-600',
          'text-red-500',
          'text-red-800',
          'text-sm',
          'text-white',
          'w-full',
        ],
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.5rem' }],
      base: ['1rem', { lineHeight: '1.75rem' }],
      lg: ['1.125rem', { lineHeight: '2rem' }],
      xl: ['1.25rem', { lineHeight: '2rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['2rem', { lineHeight: '2.5rem' }],
      '4xl': ['2.5rem', { lineHeight: '3.5rem' }],
      '5xl': ['3rem', { lineHeight: '3.5rem' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1.1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    extend: {
      borderRadius: {
        '4xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        display: ['Lexend', ...defaultTheme.fontFamily.sans],
      },
      maxWidth: {
        '2xl': '40rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
   // eslint-disable-next-line no-dupe-keys
   plugins: [require('@tailwindcss/typography')],
};
